name: Terraform CI/CD (minimal)

on:
  push:
    branches: [ main ]
  pull_request:

env:
  AWS_REGION: eu-central-1
  TF_VERSION: 1.12.2
  TF_DIR: terraform

permissions:
  id-token: write
  contents: read

jobs:
  fmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ env.TF_VERSION }}
      - run: terraform fmt -recursive
        working-directory: ${{ env.TF_DIR }}

  plan:
    needs: fmt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ env.TF_VERSION }}

      - uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::290952542819:role/GithubActionsRole
          aws-region: ${{ env.AWS_REGION }}

      - run: terraform init
        working-directory: ${{ env.TF_DIR }}
      - run: terraform plan
        working-directory: ${{ env.TF_DIR }}

  apply:
    needs: plan
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ env.TF_VERSION }}

      - uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::290952542819:role/GithubActionsRole
          aws-region: ${{ env.AWS_REGION }}

      - run: terraform init
        working-directory: ${{ env.TF_DIR }}
      - run: terraform apply -auto-approve
        working-directory: ${{ env.TF_DIR }}
